export const BUILDING_LIST_SELECT = [
  "id",
  "building_name",
  "address",
  "basement_floors",
  "ground_floors",
  "business_district",
  "gross_floor_area",
  "approval_date_parsed",
  "rental_area_pyeong",
  "deposit_total",
  "rent_total",
  "subway_walk_min",
  "lat",
  "lng",
  "thumbnail_path",
].join(",");

export const BUILDING_DETAIL_SELECT = [
  "id",
  "building_name",
  "address",
  "subway",
  "building_use",
  "etc_purpose",
  "register_classification",
  "plat_address",
  "district_unit_plan_zone",
  "national_industrial_complex",
  "basement_floors",
  "ground_floors",
  "business_district",
  "scale",
  "gross_floor_area",
  "approval_date",
  "approval_date_parsed",
  "deposit_num",
  "rent_num",
  "maintenance_num",
  "parking_fee",
  "elevator",
  "parking",
  "hvac",
  "ceiling_height",
  "lat",
  "lng",
  "is_public",
  "thumbnail_path",
].join(",");

export const BUILDING_SITEMAP_SELECT = [
  "id",
  "building_name",
  "updated_at",
].join(",");
